### ISSUE TITLE
error items

### ISSUE THREAD

**Issue by cocaocla** [opentibiabr/otservbr-global-1.0#3]
>> Loading vocations
>> Loading items
terminate called after throwing an instance of 'boost::exception_detail::clone_i                                                                                                 mpl<boost::exception_detail::error_info_injector<std::ios_base::failure[abi:cxx1                                                                                                 1]> >'
  what():  failed opening file: No such file or directory: iostream error
Aborted
Whats is problem?

**Comment by dudantas** [comment]
![image](https://user-images.githubusercontent.com/8551443/73033175-f8f5fb80-3e1f-11ea-881d-99905274c76b.png)

good evening.
please give more information ... I tested it here and everything is ok.

**Comment by cocaocla** [comment]
![blad](https://user-images.githubusercontent.com/57010926/73033277-c9f08180-3e41-11ea-9f89-99ea7743121a.png)
after compiling the server and the first attempt to fire, an error has occurred with items and I do not understand it yet

**Comment by MajestyOTBR** [comment]
Why are you trying to use OTServBR-Global-1.0? This repository is in development phase, it may contain flaws. It should only be used if you know what you are doing.

**Comment by cocaocla** [comment]
because it seems good and wonderful, you try to learn something new and learn some programming knowledge. and by the way play and look for mistakes

**Comment by dudantas** [comment]
are you using 1.0 clean? because I tested it and everything is ok.

**Comment by cocaocla** [comment]
yes i use clean i downloaded it just 20 minutes ago even less

**Comment by MajestyOTBR** [comment]
It was missing the items.otb to load the server.

**Comment by cocaocla** [comment]
ahhh .... i didn't notice. right.

**Comment by dudantas** [comment]
my sincere apologies ... i put my gitignore file to ignore .otb and for that reason did not download items.otb, update your folder with this file that everything will work.

**Comment by MajestyOTBR** [comment]
Fixed on: https://github.com/opentibiabr/otservbr-global-1.0/commit/bfa946b399d034f3d009323e98bda437dbb5081a

**Comment by dudantas** [comment]
thank you @MajestyOTBR  for watching the error.

**Comment by cocaocla** [comment]
there is nothing to apologize for. I am also sorry to poison your life :D thank you again for your help, have a nice evening
