### ISSUE TITLE
lua script error [interface] 

### ISSUE THREAD

**Issue by manifex30890** [opentibiabr/otservbr-global-1.0#4]
![image](https://user-images.githubusercontent.com/60244156/73035256-c2cc7200-3e47-11ea-8461-84fd025745a7.png)

Hello. after turning on the server errors pop up.
I didn't edit anything in the engine, I'm using debian 9.
I would attempt to repair it but I need any advice about this issue.

**Comment by lBaah** [comment]
Check this commit please and change yours accordingly: https://github.com/opentibiabr/otservbr-global-1.0/commit/bfa946b399d034f3d009323e98bda437dbb5081a
